project:
  type: website

website:
  title: "舒子豪"
  navbar:
    background: primary
    search: true
    right:
      - text: "主页"
        file: index.qmd
      - about.qmd

  reader-mode: true
  page-footer: "Copyright 2022, Zihao Shu"
format:
  html:
    theme: litera
    css: styles.css
    toc: true
about:
  template: jolla





