project:
  type: website

website:
  title: "ZihaoShu"
  navbar:
    background: primary
    search: true
    left:
      - text: "主页"
        file: index.qmd
      - sidebar:生活
      - sidebar:干货
      - about.qmd
  sidebar:
    - id: 生活
      title: "生活"
      style: "docked"
      background: light
      contents:
        - 骑行.qmd
    - text: "---"
    - id: 干货
      title: "干货"
      style: "docked"
      background: light
  reader-mode: true
  page-footer: "Copyright 2022, Zihao Shu"
format:
  html:
    theme: litera
    css: styles.css
    toc: true
about:
  template: jolla



