project:
  type: website

title-block-banner: "#3E3F3A"
title-block-banner-color: "#C5C6C4"

website:
  title: "舒子豪"
  site-url: https://shuzihao.netlify.app
  navbar:
    background: primary
    search: true
    right:
      - text: "主页"
        file: index.qmd
      - about.qmd
      - icon: rss
        href: index.xml
    pinned: true

  page-footer: "Copyright 2022, Zihao Shu"
format:
  html:
    theme: litera
    css: styles.css
    toc: true
about:
  template: marquee





