project:
  type: website

website:
  title: "舒子豪"
  site-url: https://shuzihao.netlify.app
  navbar: 
    right: 
      - text: 主页
        href: about.qmd
      - text: 博客
        menu: 
          - text: R
            href: posts/R/index.qmd
          - text: 生态学
            href: posts/生态学/index.qmd
          - text: 技术原理
            href: posts/技术原理/index.qmd
      - icon: rss
        href: index.xml
    pinned: true

  page-footer: "Copyright 2022, Zihao Shu"
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true

editor: visual




