---
title: "氨基糖的种类"
title-block-banner: false
author: "舒子豪"
date: 2022-3-4
categories: [分子生物学]
about: 
    template: marquee
---
微生物标识物氨基糖（Amino Sugar，AS）是几种结构不同的六碳糖，其在土壤中的来源主要为**微生物代谢物**以及**细胞壁的残留**这两种途径，在微生物死亡后能够在环境中长时间的保存，有着较高的稳定性和**微生物异源性**。

微生物代谢过程中产生的微生物残留物是评价微生物介导过程对土壤有机质积累贡献的有效指标。不同来源的氨基糖以及其构成的比值（GlcN/MurN、GlcN/GalN）通常被用来评估真菌和细菌在有机质转化过程中的贡献情况。

在微生物中已经鉴别出26种氨基糖，而土壤种存在11种氨基糖，利用色谱技术进行分离操作，目前可以定量测定：氨基葡萄糖（Glucosamine，GlcN）、氨基半乳糖（Galactosamine，GalN）、甘露糖胺(Mannosamine，ManN)和胞壁酸（Muramic，MurN）。

# 氨基葡萄糖（Glucosamine，GlcN）
氨基葡萄糖是这四种氨基糖中含量最高的，GlcN通常存在于真菌和细菌中，其主要来源为真菌的细胞壁，而古细菌细胞壁和无脊椎动物外骨骼来源的氨基糖在土壤中含量很低。GlcN是真菌**几丁质（Chitin）**的唯一成分，GlcN也可以在N-乙酰化后产生的衍生物质与N-乙酰胞壁酸以β-1，4-糖苷键相聚合后形成肽聚糖。

# 氨基半乳糖（Galactosamine，GalN）
氨基半乳糖是土壤中第二常见的氨基糖，GalN在以往被认为主要来源于细菌，而目前有研究表明真菌源也不可忽略。GalN可能是土壤中**胞外聚合物（Extracellular Polymeric Substance，EPS）**的重要组成部分，土壤中的胞外聚合物具有与粘蛋白相似的作用（保护胞外酶），粘蛋白是一个高分子量、高度糖基化和乙二醇结合的蛋白质族，包含高浓度的GalN，类似的粘液物质如胞外聚合物和荚膜多糖，以及附着在微生物细胞壁上的脂多糖，可能是土壤中GalN的主要来源。

# 甘露糖胺(Mannosamine，ManN)
土壤中甘露糖胺含量较低，ManN对单独某一种微生物群体无特异性没这事因为在细菌和真菌当中均有ManN的生存。研究表明在真菌的唾液酸、细菌的磷壁酸以及革兰氏阳性菌的EPS种均可以检测到ManN的存在。

# 胞壁酸（Muramic，MurN）
土壤中的胞壁酸来源于细菌，是细菌中脂多糖和细胞壁中肽聚糖的组成成分，只存在于细菌细胞壁和膜层中。其会受到相关酶的作用进而发生乙酰基化形成N-乙酰胞壁酸（N-acetyl muramic acid），并且与N-乙酰葡萄糖胺（N-acetyl-glucosamine）经β-1，4-糖苷键连接成细菌细胞壁的基本骨架。