---
title: "滨海湿地概述"
subtitle: "这很有趣"
title-block-banner: false
author: "舒子豪"
date: today
categories: [滨海湿地]
about: marquee
---
# 滨海湿地

滨海湿地（coastal wetland）指低潮时水深不足6m的水域及其沿岸浸润地带，是陆渡生态系统和海洋生态系统的交错过渡地带。滨海湿地包括：

- 滩涂湿地<br>
包括低潮线以上到高潮线之间、向陆地延伸可达10km的海岸带湿地，包括潮上带(supratidal zone)地和潮间带(intertidal zone)湿地。

:::{.callout-tip}
潮上带指位于平均高潮线与最大涨潮线之间的区域;正常潮汐作用不能到达,但在大潮或者风暴潮时,海水可以淹没,宽达数十到数百千米.
:::

:::{.callout-important}
潮间带是指平均最高潮位和最低潮位间的海岸,也就是海水涨至最高时所淹没的地方开始至潮水退到最低时露出水面的范围.
:::

- 浅海湿地<br>
或称潮下带湿地，指位于平均低潮线以下6m等深线的潮下带(subtidal zone)海域。

# 潮汐类型
潮汐是指海水在天体(主要是月球和太阳)引潮力作用下所产生的周期性运动。习惯上把海面垂直方向的涨落称为潮汐,而海水在水平方向的流动称为潮流。

:::{.callout-tip}
我们的祖先为了表示生潮的时刻,把发生在早晨的高潮称为潮,发生在晚上的高潮称为汐.
:::

根据周期潮汐可分为三类:

- 半日潮型<br>
一个太阳日内出现两次高潮和两次低潮,前一次高潮和低潮的潮差与后一次高潮和低潮的潮差大致相同,涨潮过程和落潮过程的时间也几乎相等(6h 12.5min)。我国渤海、黄海、东海的多数地点为半日潮型，如大沽、青岛、厦门等。

- 全日潮型<br>
一个太阳日内只有一次高潮和低潮，南海的北部湾是世界上最典型的全日潮海区。渤海秦皇岛也属于全日潮型。

:::{.callout-note}
北部湾的广西北海海域为不规则半日潮。
:::

- 混合潮型<br>
一个月内有些日子出现两次高潮和两次低潮，但两次高潮和低潮的潮差相差较大，涨潮过程和落潮过程的时间也不等，而另一些日子则出现一次高潮和一次低潮。<br>
我国南海多数地点属混合潮型。

:::{.callout-tip}
不论哪种潮汐类型，在农历每月初一、十五后两三天内，都要发生一次潮差最大的大潮，其时潮水涨得最高，落得最低。<br>
在农历每月初八、二十三后两三天内，各有一次潮差最小的小潮，届时潮水涨得不太高，落得不太低。
:::

